import Link from 'next/link';
import Image from 'next/image';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import InnerBanner from '@/components/InnerBanner';

export default function ServiceDetail() {
  return (
    <>
      <div className="page-wraper">
        <Header />
        
        <div className="page-content">
          <InnerBanner title="Service detail" />
          

                    

            {/*  SERVICE DETAIL SECTION START  */}
            <div className="section-full p-t120 p-b90">
                <div className="section-content">
                    <div className="container">
                        <div className="row">

                            <div className="col-lg-8 col-md-12">
                                <div className="section-content service-full-info">
                                    <div className="services-etc m-b30">
                                        <div className="wt-media m-b30">
                                            <img src="images/services/s/1.jpg" alt="" /> 
                                        </div> 
                                        <div className="wt-info">
                                            <div className="text-left">
                                                <h2 className="wt-title m-b20">Virtual Design Assistance</h2>
                                            </div>
                                            <p>Evaluate the results to be obtained from such systems or processes. concerned with the development, improvement, and implementation of inte grated systems of people, money, knowledge.</p>
                                            <p>Concerned with the development, improvement, and implementation of integrated system of people, money, knowledge, information, equipment, energy, materials, analysis and syn thesis, as well as the mathematical, physical and social sciences together with the principle and methods of engineering design to specify, predict, and evaluate the results to be obtained from such systems or processes.</p>
                                            <div className="row d-flex justify-content-center m-t30">
                                                <div className="col-lg-6 col-md-6 col-sm-6 m-b30"><img src="images/services/s/2.jpg" alt="" /></div>
                                                <div className="col-lg-6 col-md-6 col-sm-6 m-b30"><img src="images/services/s/3.jpg" alt="" /></div>
                                            </div>                                            
                                        </div>
                                        <p>Engineering is concerned with the development, improvement, and implementation of inte grated systems of people, money, knowledge, information, equipment, energy, materials, analysis and synthesis, as well as the mathematical, physical and social sciences together with the principles and methods of engineering design to specify, predict, and evaluate the results to be obtained from such systems or processes.</p>
                                        <div className="service-provide">
                                            <div className="s-single-list">
                                                <h4>Additional Amenities :</h4>
                                                <ul className="list-angle-right">
                                                    <li><span>Kid's Play Area :</span> A dedicated area for children to play</li>
                                                    <li><span>Meeting Rooms :</span> Spaces for business or social gatherings.</li>
                                                    <li><span>Shine World Cleaning Services :</span> Professional cleaning and maintenance services.</li>
                                                    <li><span>Restaurant :</span> A dining facility for residents and guests.</li>
                                                    <li><span>Medical Facility :</span> A clinic or healthcare center on-site.</li>
                                                    <li><span>Smart Home Technology :</span> Automated systems for lighting, security, and other functions.</li>
                                                    <li><span>Pet-Friendly :</span> Facilities that accommodate pets.</li>
                                                    <li><span>Green Spaces :</span> Parks, gardens, and open areas for relaxation and recreation.</li>
                                                    </ul>
                                            </div> 
                                        </div>
                                        <p>After submitting your application, our specialist will come to your home to determine the optimal amount of energy generated by solar panels, based on your electricity consumption. It’s free and doesn’t take more than 40 minutes. Next, our specialist will offer you various types of solar panels and batteries to save the accum- ulated solar energy for the day. After that, you will have time to think and you can order all the necessary equipment directly from us. We also offer discounts on our partners ‘ equipment.</p> 
                                    </div>
                                </div>
                            </div>
                        
                            <div className="col-lg-4 col-md-12 rightSidebar twm-sidebar-section">
                                <div className="all_services_list">
                                    <div className="all_services m-b30">
                                        <ul>
                                            <li><a href="services-2.html" className="active">All Services</a></li>
                                            <li><a href="services-2.html" >Architecture</a></li>
                                            <li><a href="services-2.html">Interior Design</a></li>
                                            <li><a href="services-2.html">Urban Design</a></li>
                                            <li><a href="services-2.html">3D Modelling</a></li>
                                            <li><a href="services-2.html">Decor Plan</a></li>
                                            <li><a href="services-2.html">Planning</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div className="service-side-btn m-b30">
                                    <h3 className="wt-title m-b20">Brochures</h3>
                                    <p>View our 2025 financial prospectus brochure for an easy to read guide on all of the services offer.</p>
                                    
                                    <div className="btn-block">
                                        <a href="images/poster.zip">
                                            
                                           <strong><span className="bi bi-file-earmark-pdf-fill"></span>Documentation</strong>
                                           <i className="download-btn fa fa-download"></i>
                                        </a>
                                        <a href="images/poster.zip">
                                          
                                          <strong ><span className="bi bi-file-earmark-word-fill"></span>Company Brochure</strong>
                                          <i className="download-btn fa fa-download"></i>
                                        </a>
                                        <a href="images/poster.zip">
                                          
                                          <strong><span className="bi bi-file-earmark-play-fill"></span>Company Report 2025</strong>
                                          <i className="download-btn fa fa-download"></i>
                                        </a>
                                    </div>
                                                                
                                </div>
                            </div>
                            
                        </div>                            
                    </div>                                 
                </div>
            </div>   
            {/*  SERVICE DETAIL SECTION END  */} 
     
        
        </div>
        
        <Footer />
      </div>
    </>
  );
}